### ISSUE TITLE
Bug with Grafana 7.4.X

### ISSUE THREAD

**Issue by thomasbromkapsdata** [SSKGo/perfcurve-panel#13]
Hello,

Plugin doesn't work with Grafana 7.4.X but is OK with Grafana 7.3.1.
There is the "red i" in the hight left corner with:
`Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings`

The adresse lead to:
`
The full text of the error you just encountered is:
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.
`

**Comment by SSKGo** [comment]
@thomasbromkapsdata 

Thank you for raising this issue.
The reported error happen when the plugin version before 1.3.1 was used in Grafana 7.4.X (the current latest version).
I released [V1.4.0](https://github.com/SSKGo/perfcurve-panel/releases/tag/v1.4.0) to solve the problem and requested to add it in the official catalog.

This problem happened because a component which was used to indicate legend in the panel was suddenly replaced with a new component at version-up to 7.4.X.

**Comment by SSKGo** [comment]
@thomasbromkapsdata 

V1.4.0 has been released in the official catalog.

I close this issue.

https://grafana.com/grafana/plugins/sskgo-perfcurve-panel?pg=plugins&plcmt=featured-undefined&version=1.4.0
